#!/usr/bin/env bash
#
# Renders docs/keybindings.md from hypr/config/software/keybinds.conf.
#
# README used to carry the full table by hand. It drifted, exactly the way the
# rofi cheatsheet drifted before it was made self-rendering: bindings the config
# does not have, bindings the config has that the table omitted, and per-user
# values printed as though they were fixed. Moving a hand-written table to a new
# file relocates that problem, so this generates it instead.
#
# The rows come from `keybinds-cheatsheet.sh --markdown` rather than from a
# second parser here. One parse feeds both surfaces, so the document and the
# Super+H sheet cannot disagree; this script only supplies the prose around it.
#
# Usage: generate-keybindings.sh [--check]
#   (no args)  write docs/keybindings.md
#   --check    exit 1 with a diff when the tracked file is out of date;
#              this is what test/test-docs.sh runs.
#
set -uo pipefail

self_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$self_dir/../.." && pwd)"

cheatsheet="$root/rofi/keybinds-cheatsheet.sh"
out="$root/docs/keybindings.md"

if [ ! -x "$cheatsheet" ]; then
    echo "generate-keybindings: cannot run $cheatsheet" >&2
    exit 1
fi

render() {
    cat <<'PREAMBLE'
<!-- Generated by scripts/docs/generate-keybindings.sh. Do not edit by hand. -->

# Keybindings

Every row below is rendered from `hypr/config/software/keybinds.conf` by the
same parse that `Super + H` shows at runtime, so this file cannot disagree with
the bindings it documents. To change a binding, edit the config and regenerate:

```bash
./scripts/docs/generate-keybindings.sh
```

`test/test-docs.sh` fails when this file is out of date, so a stale copy cannot
be committed.

Two rows name a file rather than an application. `Super + Enter` and
`Super + B` run whatever `options/terminal` and `options/browser` contain, read
at Hyprland's parse time, so the answer is per-machine and the runtime
cheatsheet fills in your own. Everything else here is the same on every
checkout.

PREAMBLE
    "$cheatsheet" --markdown
}

if [ "${1:-}" = "--check" ]; then
    if [ ! -f "$out" ]; then
        echo "generate-keybindings: $out does not exist" >&2
        exit 1
    fi
    # Process substitution, not a pipe: the exit status has to be diff's.
    if ! diff -u "$out" <(render) >/dev/null; then
        echo "docs/keybindings.md is out of date. Regenerate with:" >&2
        echo "  ./scripts/docs/generate-keybindings.sh" >&2
        diff -u "$out" <(render) >&2
        exit 1
    fi
    exit 0
fi

render > "$out"
echo "wrote ${out#"$root"/}"
