# System UI Components
exec-once = waybar
exec-once = swaync
exec-once = swayosd-server &

# Wallpaper Management
exec-once = awww-daemon
exec-once = $HOME/.config/scripts/hyprland/restore-wallpaper.sh
exec-once = $HOME/.config/sddm/watch_wallpaper.sh &

# System Services
exec-once = hypridle
exec-once = $polkitAgent
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# AGS Settings Panel
exec-once = ags run $HOME/.config/ags/app.ts &

# User Startup Script
exec-once = $HOME/.config/scripts/hyprland/startup.sh
